name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install Python Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools wheel
      - name: Build Distributions
        run: python setup.py sdist bdist_wheel
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Change Log:
          draft: true  # Give me a moment to fill in the description
          prerelease: false
          artifacts: "dist/*"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
