name: tests

on:
  pull_request:
  push:
    paths:
      - '**.py'
      - '**.yml'
      - 'requirements.txt'
  schedule:
    # Test master every Saturday at midnight to verify dependencies
    - cron:  '0 0 * * 6'

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install flake8
      - name: Check
        run: python -m flake8 httpx_gssapi
  test:
    name: Test
    needs: flake8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v1
      - name: Setup Build Tools
        run: sudo apt-get install -y krb5-kdc libkrb5-dev
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U -r requirements.txt pytest-coverage codecov
      - name: Run Tests
        run: python -m pytest --cov=httpx_gssapi --cov-report=xml
      # - name: Upload Coverage
      # run: python -m codecov --token=${{ secrets.CODECOV_TOKEN }}
